apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
spec:
  tls:
  - hosts:
    - pihole.local
  rules:
  - host: pihole.local
    http:
      paths:
      - backend:
          serviceName: pihole
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-configmap
  labels:
    app: pihole
data:
  DNS1: 1.0.0.1
  DNS2: 142.168.200.5
---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secrets
  labels:
    app: pihole
type: Opaque
data:
  WEBPASSWORD: BASE64ENCODEDPASSWORDGOESHERE
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole
          ports:
            - containerPort: 80
            - name: dns
              containerPort: 53
              hostPort: 53
              protocol: UDP
          envFrom:
            - configMapRef:
                name: pihole-configmap
            - secretRef:
                name: pihole-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: pihole
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
   - name: dns
     port: 53
     targetPort: 53
     protocol: UDP            
